version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - gu install native-image
    on-failure: ABORT
  build:
    commands:
      - echo Build started on `date`
      - java -jar /leiningen-2.9.3-standalone.jar -m leiningen.core.main install
      - cd lambda
      - java -jar /leiningen-2.9.3-standalone.jar -m leiningen.core.main uberjar
      - native-image -jar target/menard-lambda.jar menard_lambda --report-unsupported-elements-at-runtime --no-fallback --verbose --enable-url-protocols=http,https --no-server  --initialize-at-build-time --initialize-at-build-time=org.apache.log4j.CategoryKey --trace-object-instantiation=java.lang.Thread
      - cp bootstrap menard_lambda /
      - cp template-native.yml /
      - ls -l /
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /bootstrap
    - /output
    - /template-native.yml
