AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Menard lambda functions using using the `holy-lambda` micro library"
Parameters:
  Runtime:
    Type: String
    Default: provided
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
  BucketName:
    Type: String
  ObjectKey:
    Type: String
Globals:
  Function:
    Runtime: !Ref 'Runtime'
    Timeout: !Ref 'Timeout'
    MemorySize: !Ref 'MemorySize'
Resources:
  AnalyzeEN:
    Type: AWS::Serverless::Function
    Properties:
      Handler: menard.lambda.def.AnalyzeEN
      CodeUri:
        Key: !Ref 'ObjectKey'
        Bucket: !Ref 'BucketName'
      FunctionName: AnalyzeEN
      Events:
        Event:
          Type: Api
          Properties:
            Path: /analyze/en
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
          Type: AllAtOnce
